### ISSUE TITLE
Sync with latest version of DocuSign API

### ISSUE THREAD

**Issue by neilberkman** [neilberkman/docusign_elixir#21]
The generated code in [lib/docusign](../tree/master/lib/docusign) is out of date and should be updated to reflect the latest DocuSign API spec. There are instructions for doing this in the [README](https://github.com/neilberkman/docusign_elixir#regenerating-stubs). I tried this myself and got errors when running tests so I'm hoping that someone with more time than I currently have can look into this.

**Comment by frahugo** [comment]
I was able to generate it using the Docker version of the generator. I will submit a PR soon.

**Comment by neilberkman** [comment]
Thanks @frahugo really appreciate it!

**Comment by frahugo** [comment]
@neilberkman The code gets generated, but it does not compile. Is that the error you are getting?

```
== Compilation error in file lib/docusign/api/account_brands.ex ==
** (CompileError) lib/docusign/api/account_brands.ex:353: cannot invoke remote function :erlang.//2 inside a match
    lib/docusign/api/account_brands.ex:348: (module)
```

A function parameter is badly named:

```
  def brand_resources_put_brand_resources(
        connection,
        account_id,
        brand_id,
        resource_content_type,
        file / xml,
        _opts \\ []
      ) do
    %{}
    |> method(:put)
    |> url("/v2.1/accounts/#{account_id}/brands/#{brand_id}/resources/#{resource_content_type}")
    |> add_param(:file, :"file.xml", file / xml)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%DocuSignRESTAPI.Model.BrandResources{})
  end
```

**Comment by neilberkman** [comment]
@frahugo in my case It complied but the tests failed. I don't remember the specifics and I don't have the code at this point.

**Comment by frahugo** [comment]
Alright. After renaming that argument and restore some files that were deleted after the `rm -rf lib/docusign/*` step in the README, I got the tests green. Will try the API from the command line now.

**Comment by frahugo** [comment]
Some API functions do work. But I ended up trying to get the document tabs from a template and found out that the generated code references the wrong module:

```
    |> deserialize(:dateTabs, :list, DocuSign.Model.DateTime, options)
```

`dateTabs` are not properly deserialized throughout the code. It should be using `DocuSign.Model.Date`. I looked at the API json, and the definition seems correct. 

I cannot test the entire code base. We should be able to rely on the generated code. I wonder if the problem is with the swagger code. Maybe switching to the OpenAPI generator would solve those issues? I'll investigate.

**Comment by frahugo** [comment]
Well, things are not better with the [OpenAPI generator](https://github.com/OpenAPITools/openapi-generator). I tried the "docker" way of generating code, but it runs out of memory. Tried in "dev-docker" way, and it still runs out of memory (later, but it does). Seems to be an infinite loop. Tried with different versions of the DocuSign 2.1 json specs, all with problems. Tried other version of OpenAPI generator, and still no success. I tried generating the API code for ruby and python: no success. The OpenAPI generator has +2K open issues, that is not a good sign.

DocuSign states that their specification files are "valid". So I guess the issue is with the code generators. 

Strangely, if I generate the code for v2.0, it works like a charm. Go figure.

Asked DocuSign for some help: https://github.com/docusign/OpenAPI-Specifications/issues/39

**Comment by neilberkman** [comment]
@frahugo are you still using the library? If so, would you have time to try out PR #33 to see if everything still works for you? If you would have time to review it as well, that would be very helpful. Of course I understand if you're not able to.

**Comment by frahugo** [comment]
Yes I am. Will try PR #33 today and report on it. Thanks.

**Comment by frahugo** [comment]
@neilberkman 

I provided a comment on the PR regarding the downgrade of Poison, and a question to the contributor (I'm having an issue getting list of templates).

**Comment by neilberkman** [comment]
@frahugo excellent, thanks!

**Comment by neilberkman** [comment]
Closed by https://github.com/neilberkman/docusign_elixir/pull/33
